export const contextualHelp = {
  accountType: {
    title: "Account Type",
    explanation: "Choose whether you are setting up Advisacor for your own company, a bookkeeping/advisory practice, or a fractional CFO firm.",
    why: "Advisacor uses this to create the right account structure: one company, a solo practice with clients, or a multi-client firm workspace.",
    example: "A business owner would choose My Own Company. A side bookkeeper with clients would choose Bookkeeper / Advisor Managing Clients.",
    impact: "This controls the onboarding path, user setup, client management, and future firm dashboards.",
  },
  companyName: {
    title: "Company Name",
    explanation: "The legal or operating name of the company being analyzed.",
    why: "Advisacor uses this name across dashboards, reports, emails, audit logs, and generated packages.",
    example: "Wiseman Manufacturing LLC",
    impact: "This appears in executive summaries, PDF/PPT packages, client workspaces, and email delivery.",
  },
  industry: {
    title: "Industry Description",
    explanation: "A short plain-English description of what the company does.",
    why: "This gives Advisacor extra business context beyond the fixed industry category.",
    example: "Commercial construction, skilled nursing facility, or B2B SaaS platform.",
    impact: "This context can improve executive wording, AI commentary, and management focus areas.",
  },
  industryType: {
    title: "Industry Type",
    explanation: "The primary industry category for the company.",
    why: "Advisacor uses this to choose the right KPIs, dashboard emphasis, executive summaries, AI commentary, and industry intelligence modules.",
    example: "Healthcare enables patient-day metrics. Manufacturing enables inventory, PPV, BOM, and labor variance focus.",
    impact: "This is foundational for industry-aware dashboards, benchmarking, recommendations, and future operational intelligence.",
  },
  revenueRange: {
    title: "Revenue Range",
    explanation: "The approximate annual revenue size of the company.",
    why: "Advisacor uses company size to tailor recommendations, package expectations, and future benchmarking comparisons.",
    example: "$5M-$25M",
    impact: "This helps compare the company to more relevant peers and avoid recommendations that fit a much smaller or larger business.",
  },
  employeeCount: {
    title: "Employee Count",
    explanation: "The approximate number of employees or full-time equivalents.",
    why: "Advisacor uses staffing information for payroll, FTE, productivity, and workforce intelligence.",
    example: "42 employees",
    impact: "This supports revenue per employee, payroll efficiency, staffing trends, and role-specific executive commentary.",
  },
  accountingSystem: {
    title: "Accounting System",
    explanation: "The accounting platform or input method that will provide financial data.",
    why: "Advisacor connects, discovers available reports, validates missing data, and recommends the right package automatically.",
    example: "QuickBooks Online, QuickBooks Desktop, QuickBooks Enterprise, Xero, NetSuite, Sage, Microsoft Dynamics, or Manual Financial Upload.",
    impact: "This controls report discovery, package recommendation, first-package generation, recurring updates, and future integration behavior.",
  },
  reportingCadence: {
    title: "Reporting Cadence",
    explanation: "How often the company expects reporting and executive updates.",
    why: "Advisacor uses cadence to schedule briefs, packages, reviews, reminders, and background jobs.",
    example: "Weekly for owner snapshots, monthly for financial packages, quarterly for board-style reviews.",
    impact: "This affects delivery timing, dashboard freshness, executive emails, and review workflows.",
  },
  primaryUseCase: {
    title: "Primary Use Case",
    explanation: "The main audience Advisacor should optimize for by default.",
    why: "The same financial intelligence is translated differently for owners, bookkeepers, controllers, and fractional CFOs.",
    example: "Business Owner uses plain English. Controller focuses on close quality. Fractional CFO focuses on board-ready strategy.",
    impact: "This changes output style, dashboard emphasis, AI tone, recommendations, and report language.",
  },
  packageSelection: {
    title: "Package Recommendation",
    explanation: "The depth of intelligence available to the company.",
    why: "Advisacor uses package level to determine which intelligence modules, reports, and recommendations are included.",
    example: "Essential covers AP/AR/payroll basics. Professional adds working capital and operations. Virtual CFO adds forecasting, treasury, and executive guidance.",
    impact: "This controls available dashboards, report sections, AI context, and advisory depth.",
  },
  dataSource: {
    title: "Data Connection",
    explanation: "Choose the fastest path for your first package: connect an accounting system for full intelligence or upload financial statements for a fast free report.",
    why: "Advisacor needs financial data before it can create a meaningful executive summary, dashboard, and package.",
    example: "Connect QuickBooks Online/Desktop/Enterprise for full report discovery, or upload a Balance Sheet and Income Statement for a limited sample report.",
    impact: "Manual upload creates fast value with limited analysis. Connected accounting unlocks automated updates, briefs, packages, forecasting, budgeting, industry intelligence, and AI.",
  },
  recipientEmails: {
    title: "Recipient Emails",
    explanation: "The people who should receive briefs, packages, or delivery notifications.",
    why: "Advisacor needs recipients to route executive emails and package links to the right users.",
    example: "owner@example.com, controller@example.com",
    impact: "This controls who receives weekly briefs, monthly packages, approval requests, and report links.",
  },
  approvalRequired: {
    title: "Approval Required",
    explanation: "Whether a person must review content before Advisacor sends it.",
    why: "Some teams want controller or advisor approval before executive emails or packages go out.",
    example: "Require approval before sending the monthly owner package.",
    impact: "This changes background job status, delivery timing, and review queue behavior.",
  },
  autoSend: {
    title: "Auto-Send",
    explanation: "Whether Advisacor should send approved outputs automatically.",
    why: "Auto-send reduces manual work, but some firms prefer a final review step.",
    example: "Auto-send weekly owner briefs every Friday morning.",
    impact: "This affects delivery automation, approvals, and audit logs.",
  },
  inviteUsers: {
    title: "Invite Users",
    explanation: "Add people who should access the company or client workspace.",
    why: "Advisacor uses roles to decide what each person can see and manage.",
    example: "Invite an owner as Owner/Executive and a controller as Controller.",
    impact: "This controls permissions, dashboard visibility, report access, and preparer vs executive views.",
  },
  userRole: {
    title: "User Role",
    explanation: "The access level for an invited user.",
    why: "Different users need different visibility. Owners should not see preparer-only details, while controllers need close review tools.",
    example: "Owner/Executive, Controller, Bookkeeper, Advisor, or Viewer.",
    impact: "This controls permissions, private route access, package generation, and role-appropriate dashboards.",
  },
  deliveryDay: {
    title: "Delivery Day",
    explanation: "The day Advisacor should prepare or send recurring outputs.",
    why: "This helps schedule weekly briefs, monthly packages, and internal review timing.",
    example: "Friday for weekly owner briefs or 5th business day for monthly packages.",
    impact: "This affects background jobs, reminders, approval queues, and executive delivery timing.",
  },
  packageType: {
    title: "Package Type",
    explanation: "The style of report or package being delivered.",
    why: "Different audiences need different output formats and levels of detail.",
    example: "Weekly KPI Snapshot, Executive Financial Package, or Board Review Package.",
    impact: "This affects report structure, included sections, and AI-generated summary style.",
  },
};

export function getContextualHelp(key) {
  return contextualHelp[key] || null;
}
