/**
 * scripts/gen-tsa-trust-bundle.ts
 *
 * Reads public/tsa-roots/*.pem at build time, hashes each cert's DER form,
 * and emits lib/pilot-lifecycle/generated/tsa-trust-bundle.ts as a compile-time
 * constant module. This lets the browser verifier import trusted roots without
 * runtime network I/O.
 *
 * Run:  npx tsx scripts/gen-tsa-trust-bundle.ts
 * Also wired into `predev`/`prebuild` in package.json.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";

const PEM_DIR = "public/tsa-roots";
const OUT_DIR = "lib/pilot-lifecycle/generated";
const OUT_FILE = join(OUT_DIR, "tsa-trust-bundle.ts");

function pemToDer(pem: string): Uint8Array {
  const b64 = pem
    .replace(/-----BEGIN CERTIFICATE-----/g, "")
    .replace(/-----END CERTIFICATE-----/g, "")
    .replace(/\s+/g, "");
  const bin = Buffer.from(b64, "base64");
  return new Uint8Array(bin);
}

function sha256Hex(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function bytesToTsLiteral(bytes: Uint8Array): string {
  const chunks: string[] = [];
  for (let i = 0; i < bytes.length; i += 32) {
    chunks.push(
      Array.from(bytes.slice(i, i + 32))
        .map((b) => "0x" + b.toString(16).padStart(2, "0"))
        .join(", "),
    );
  }
  return `new Uint8Array([\n    ${chunks.join(",\n    ")},\n  ])`;
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const files = readdirSync(PEM_DIR)
    .filter((f) => f.endsWith(".pem"))
    .sort();
  if (files.length === 0) {
    throw new Error(`No PEM files in ${PEM_DIR}`);
  }

  const entries = files.map((filename) => {
    const pem = readFileSync(join(PEM_DIR, filename), "utf8");
    const der = pemToDer(pem);
    const fingerprint = sha256Hex(der);
    return { filename, der, fingerprint };
  });

  const banner = `/**
 * AUTO-GENERATED by scripts/gen-tsa-trust-bundle.ts — DO NOT EDIT.
 *
 * Trusted TSA root certificates, hash-pinned. Each entry is the raw DER of a
 * PEM in public/tsa-roots/, along with its SHA-256 fingerprint. The verifier
 * matches chain-terminal certs against TRUSTED_ROOT_FINGERPRINTS using constant-time
 * byte comparison — NOT by DN or by presence in the array (order-independent).
 *
 * Generated at: ${new Date().toISOString()}
 */

`;

  const body =
    banner +
    `export type TrustedRoot = {
  filename: string;
  fingerprintHex: string; // lowercase, 64 chars, SHA-256(DER)
  der: Uint8Array;
};

export const TRUSTED_ROOTS: readonly TrustedRoot[] = [
` +
    entries
      .map(
        (e) => `  {
    filename: ${JSON.stringify(e.filename)},
    fingerprintHex: ${JSON.stringify(e.fingerprint)},
    der: ${bytesToTsLiteral(e.der)},
  },`,
      )
      .join("\n") +
    `
] as const;

export const TRUSTED_ROOT_FINGERPRINTS: ReadonlySet<string> = new Set(
  TRUSTED_ROOTS.map((r) => r.fingerprintHex),
);
`;

  writeFileSync(OUT_FILE, body, "utf8");
  console.log(`Wrote ${OUT_FILE} — ${entries.length} trusted roots:`);
  for (const e of entries) {
    console.log(`  ${e.fingerprint}  ${e.filename}`);
  }
}

main();
