create table if not exists public.company_memory_records (
  memory_id text primary key,
  memory_group_id text not null,
  memory_key text not null,
  record_version integer not null,
  company_id uuid not null,
  memory_type text not null,
  memory_status text not null,
  persistence_status text not null default 'pending',
  governance_status text,
  refresh_status text,
  intelligence_scope text,
  intelligence_record_type text,
  domain text,
  subdomain text,
  topic text,
  industry text,
  entity_scope text,
  entity_type text,
  entity_id text,
  consolidation_group_id text,
  source_system text,
  tenant_id text,
  record_input_id text,
  record_input_determinism_hash text,
  persistence_determinism_hash text,
  confidence_score numeric,
  confidence_reason text,
  evidence_strength text,
  data_completeness_score numeric,
  audience_level text,
  legal_hold boolean not null default false,
  retention_expires_at timestamptz,
  candidate_id text,
  promotion_id text,
  approval_id text,
  approved_by text,
  approved_at timestamptz,
  approval_reason text,
  promoted_by text,
  promoted_at timestamptz,
  promoted_version text,
  promotion_reason text,
  retired_by text,
  retired_at timestamptz,
  retired_reason text,
  archived_at timestamptz,
  superseded_at timestamptz,
  persisted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  scenario_metadata jsonb not null default '{}'::jsonb,
  external_signal_metadata jsonb not null default '{}'::jsonb,
  governance_metadata jsonb not null default '{}'::jsonb,
  evidence_metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.company_memory_record_sources (
  source_id text primary key,
  memory_id text not null,
  memory_group_id text not null,
  company_id uuid not null,
  source_type text not null,
  source_system text,
  source_record_id text,
  source_report text,
  source_period text,
  source_last_updated timestamptz,
  source_reference_id text,
  snapshot_id text,
  period_key text,
  tenant_id text,
  entity_scope text,
  entity_type text,
  entity_id text,
  consolidation_group_id text,
  payload_hash text,
  normalized_data_hash text,
  source_set_hash text,
  evidence_summary text,
  source_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.company_memory_record_lineage (
  lineage_id text primary key,
  memory_id text not null,
  memory_group_id text not null,
  company_id uuid not null,
  record_input_id text,
  candidate_id text,
  promotion_id text,
  approval_id text,
  retrieval_id text,
  retrieval_lineage_id text,
  record_input_determinism_hash text,
  promotion_determinism_hash text,
  retrieval_determinism_hash text,
  persistence_determinism_hash text,
  source_reference_ids text[] not null default array[]::text[],
  snapshot_ids text[] not null default array[]::text[],
  lineage_hash text,
  source_set_hash text,
  lineage_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.company_memory_record_audit (
  audit_id text primary key,
  company_id uuid not null,
  memory_id text,
  memory_group_id text,
  event_type text not null,
  event_hash text,
  persistence_run_id text,
  request_id text,
  previous_memory_id text,
  new_memory_id text,
  previous_status text,
  new_status text,
  previous_governance_status text,
  new_governance_status text,
  persistence_actor text,
  persistence_source text,
  actor_user_id uuid,
  audit_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.company_memory_record_versions (
  version_id text primary key,
  company_id uuid not null,
  memory_group_id text not null,
  memory_id text not null,
  memory_key text not null,
  record_version integer not null,
  version_status text not null,
  superseded_by_memory_id text,
  superseded_at timestamptz,
  supersession_reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.company_memory_record_retention_events (
  retention_event_id text primary key,
  company_id uuid not null,
  memory_id text,
  memory_group_id text,
  event_type text not null,
  event_hash text,
  legal_hold_before boolean,
  legal_hold_after boolean,
  retention_expires_at_before timestamptz,
  retention_expires_at_after timestamptz,
  archive_reason text,
  supersession_reason text,
  restore_reason text,
  actor_user_id uuid,
  persistence_actor text,
  persistence_source text,
  retention_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
